trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Security static source code analysis@2019
  inputs:
    CheckmarxService: 'checkmarxIntegration'
    projectName: 'DemoProj'
    preset: 'Checkmarx Default'
    fullTeamName: 'Demo'
    incScan: true
- script: pwd
- script: ls -alh
  displayName: 'SHOW WORKING DIR'
