# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: CHDIR
- script: DIR
  displayName: 'SHOW WORKING DIR'

- script: docker run --rm --volume $PWD/WebGoat:/tmp/app -w /tmp/app microsoft/dotnet:runtime add src/WebGoat.NET.csproj package SecurityCodeScanVS2017
  displayName: 'Run Scanner'

