# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- script: CHDIR
#- script: DIR
#  displayName: 'SHOW WORKING DIR'
#- powershell: dotnet add WebGoat\WebGoat.NET.csproj package SecurityCodeScanVS2017
#- script: docker run --rm --volume %cd%\WebGoat:C:\app -w c:\app microsoft/dotnet:runtime add src/WebGoat.NET.csproj package SecurityCodeScanVS2017
 - script: docker run --rm --volume $PWD/WebGoat:/tmp/app -w /tmp/app microsoft/dotnet:2.0-sdk dotnet add WebGoat.NET.csproj package SecurityCodeScanVS2017
   displayName: 'Run Scanner'

